name: aws-reacource-tracker@v1
on:
    schedule:
        - cron: "*/1 * * * *"

jobs:
    run-tasks:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Run a script
              run: echo "This workflow runs per min"