name: schedule

on:
  schedule:
    - cron: "*/1 * * * *"

jobs:
  run-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run a script or command
        run: echo "This runs every minute"
