name: Scheduled Workflow

on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  scheduled-job:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Run a sample script
      run: echo "This job runs every  minute"